// elements.js — Full 118-element dataset
const ELEMENTS = [
  {n:1,sym:"H",name:"Hydrogen",mass:"1.008",group:"nonmetal",period:1,col:1,config:"1s¹",state:"Gas",desc:"The lightest and most abundant element in the universe, fundamental to stars and water."},
  {n:2,sym:"He",name:"Helium",mass:"4.003",group:"noble-gas",period:1,col:18,config:"1s²",state:"Gas",desc:"The second lightest element, used in balloons and as a cooling agent for superconductors."},
  {n:3,sym:"Li",name:"Lithium",mass:"6.941",group:"alkali",period:2,col:1,config:"[He] 2s¹",state:"Solid",desc:"A soft silver-white metal essential in rechargeable batteries and mood-stabilizing medication."},
  {n:4,sym:"Be",name:"Beryllium",mass:"9.012",group:"alkaline",period:2,col:2,config:"[He] 2s²",state:"Solid",desc:"A strong, lightweight metal used in aerospace and nuclear industries."},
  {n:5,sym:"B",name:"Boron",mass:"10.81",group:"metalloid",period:2,col:13,config:"[He] 2s² 2p¹",state:"Solid",desc:"A metalloid used in glass, ceramics, and as a neutron absorber in nuclear reactors."},
  {n:6,sym:"C",name:"Carbon",mass:"12.011",group:"nonmetal",period:2,col:14,config:"[He] 2s² 2p²",state:"Solid",desc:"The basis of all known life, existing as diamond, graphite, graphene, and fullerenes."},
  {n:7,sym:"N",name:"Nitrogen",mass:"14.007",group:"nonmetal",period:2,col:15,config:"[He] 2s² 2p³",state:"Gas",desc:"Makes up 78% of Earth's atmosphere and is essential for proteins and DNA."},
  {n:8,sym:"O",name:"Oxygen",mass:"15.999",group:"nonmetal",period:2,col:16,config:"[He] 2s² 2p⁴",state:"Gas",desc:"Essential for combustion and respiration, the third most abundant element in the universe."},
  {n:9,sym:"F",name:"Fluorine",mass:"18.998",group:"halogen",period:2,col:17,config:"[He] 2s² 2p⁵",state:"Gas",desc:"The most electronegative element, highly reactive and used in toothpaste and Teflon."},
  {n:10,sym:"Ne",name:"Neon",mass:"20.180",group:"noble-gas",period:2,col:18,config:"[He] 2s² 2p⁶",state:"Gas",desc:"Famous for glowing orange-red in signs, one of the least reactive elements known."},
  {n:11,sym:"Na",name:"Sodium",mass:"22.990",group:"alkali",period:3,col:1,config:"[Ne] 3s¹",state:"Solid",desc:"A highly reactive metal crucial to biological processes, table salt's key component."},
  {n:12,sym:"Mg",name:"Magnesium",mass:"24.305",group:"alkaline",period:3,col:2,config:"[Ne] 3s²",state:"Solid",desc:"A lightweight structural metal used in alloys, fireworks, and chlorophyll."},
  {n:13,sym:"Al",name:"Aluminum",mass:"26.982",group:"post-transition",period:3,col:13,config:"[Ne] 3s² 3p¹",state:"Solid",desc:"The most abundant metal in Earth's crust, lightweight and corrosion-resistant."},
  {n:14,sym:"Si",name:"Silicon",mass:"28.086",group:"metalloid",period:3,col:14,config:"[Ne] 3s² 3p²",state:"Solid",desc:"The foundation of semiconductor technology and the second most abundant element in Earth's crust."},
  {n:15,sym:"P",name:"Phosphorus",mass:"30.974",group:"nonmetal",period:3,col:15,config:"[Ne] 3s² 3p³",state:"Solid",desc:"Essential for DNA, ATP, and bones. White phosphorus is highly flammable."},
  {n:16,sym:"S",name:"Sulfur",mass:"32.06",group:"nonmetal",period:3,col:16,config:"[Ne] 3s² 3p⁴",state:"Solid",desc:"A bright yellow solid used in fertilizers, gunpowder, and rubber vulcanization."},
  {n:17,sym:"Cl",name:"Chlorine",mass:"35.45",group:"halogen",period:3,col:17,config:"[Ne] 3s² 3p⁵",state:"Gas",desc:"A yellow-green gas used in water disinfection and as a chemical weapon in WWI."},
  {n:18,sym:"Ar",name:"Argon",mass:"39.948",group:"noble-gas",period:3,col:18,config:"[Ne] 3s² 3p⁶",state:"Gas",desc:"The third most abundant gas in Earth's atmosphere, used in welding and light bulbs."},
  {n:19,sym:"K",name:"Potassium",mass:"39.098",group:"alkali",period:4,col:1,config:"[Ar] 4s¹",state:"Solid",desc:"Essential electrolyte for heart and nerve function, reacts violently with water."},
  {n:20,sym:"Ca",name:"Calcium",mass:"40.078",group:"alkaline",period:4,col:2,config:"[Ar] 4s²",state:"Solid",desc:"The most abundant metal in the human body, essential for bones and teeth."},
  {n:21,sym:"Sc",name:"Scandium",mass:"44.956",group:"transition",period:4,col:3,config:"[Ar] 3d¹ 4s²",state:"Solid",desc:"A rare transition metal used in aerospace alloys and sports equipment."},
  {n:22,sym:"Ti",name:"Titanium",mass:"47.867",group:"transition",period:4,col:4,config:"[Ar] 3d² 4s²",state:"Solid",desc:"Strong as steel but much lighter, used in aerospace, medical implants, and white paint."},
  {n:23,sym:"V",name:"Vanadium",mass:"50.942",group:"transition",period:4,col:5,config:"[Ar] 3d³ 4s²",state:"Solid",desc:"Used in steel alloys for tools and is essential to certain marine organisms."},
  {n:24,sym:"Cr",name:"Chromium",mass:"51.996",group:"transition",period:4,col:6,config:"[Ar] 3d⁵ 4s¹",state:"Solid",desc:"Gives stainless steel its anti-corrosion properties; chromium VI is toxic."},
  {n:25,sym:"Mn",name:"Manganese",mass:"54.938",group:"transition",period:4,col:7,config:"[Ar] 3d⁵ 4s²",state:"Solid",desc:"Critical in steel production and essential for enzyme function in organisms."},
  {n:26,sym:"Fe",name:"Iron",mass:"55.845",group:"transition",period:4,col:8,config:"[Ar] 3d⁶ 4s²",state:"Solid",desc:"The most abundant element by mass on Earth, cornerstone of civilization as steel."},
  {n:27,sym:"Co",name:"Cobalt",mass:"58.933",group:"transition",period:4,col:9,config:"[Ar] 3d⁷ 4s²",state:"Solid",desc:"Magnetic metal used in batteries, alloys, and the blue pigment used since antiquity."},
  {n:28,sym:"Ni",name:"Nickel",mass:"58.693",group:"transition",period:4,col:10,config:"[Ar] 3d⁸ 4s²",state:"Solid",desc:"Corrosion-resistant metal used in coins, stainless steel, and batteries."},
  {n:29,sym:"Cu",name:"Copper",mass:"63.546",group:"transition",period:4,col:11,config:"[Ar] 3d¹⁰ 4s¹",state:"Solid",desc:"One of the first metals used by humans, excellent conductor of heat and electricity."},
  {n:30,sym:"Zn",name:"Zinc",mass:"65.38",group:"transition",period:4,col:12,config:"[Ar] 3d¹⁰ 4s²",state:"Solid",desc:"Essential trace element, used in galvanizing steel and in sunscreen."},
  {n:31,sym:"Ga",name:"Gallium",mass:"69.723",group:"post-transition",period:4,col:13,config:"[Ar] 3d¹⁰ 4s² 4p¹",state:"Solid",desc:"Melts in your hand (30°C), used in semiconductors and LEDs."},
  {n:32,sym:"Ge",name:"Germanium",mass:"72.630",group:"metalloid",period:4,col:14,config:"[Ar] 3d¹⁰ 4s² 4p²",state:"Solid",desc:"A metalloid predicted by Mendeleev before its discovery, used in fiber optics."},
  {n:33,sym:"As",name:"Arsenic",mass:"74.922",group:"metalloid",period:4,col:15,config:"[Ar] 3d¹⁰ 4s² 4p³",state:"Solid",desc:"A toxic metalloid infamous as a poison, also used in semiconductors."},
  {n:34,sym:"Se",name:"Selenium",mass:"78.971",group:"nonmetal",period:4,col:16,config:"[Ar] 3d¹⁰ 4s² 4p⁴",state:"Solid",desc:"Photoconductive element used in solar cells and essential in small amounts for health."},
  {n:35,sym:"Br",name:"Bromine",mass:"79.904",group:"halogen",period:4,col:17,config:"[Ar] 3d¹⁰ 4s² 4p⁵",state:"Liquid",desc:"One of only two liquid elements at room temperature, used in flame retardants."},
  {n:36,sym:"Kr",name:"Krypton",mass:"83.798",group:"noble-gas",period:4,col:18,config:"[Ar] 3d¹⁰ 4s² 4p⁶",state:"Gas",desc:"Once used to define the meter, now used in specialized lighting and lasers."},
  {n:37,sym:"Rb",name:"Rubidium",mass:"85.468",group:"alkali",period:5,col:1,config:"[Kr] 5s¹",state:"Solid",desc:"Highly reactive alkali metal used in atomic clocks and research."},
  {n:38,sym:"Sr",name:"Strontium",mass:"87.62",group:"alkaline",period:5,col:2,config:"[Kr] 5s²",state:"Solid",desc:"Gives fireworks a brilliant crimson color; Sr-90 is a dangerous nuclear fallout product."},
  {n:39,sym:"Y",name:"Yttrium",mass:"88.906",group:"transition",period:5,col:3,config:"[Kr] 4d¹ 5s²",state:"Solid",desc:"Used in LEDs, lasers, and superconductors; named after the village Ytterby, Sweden."},
  {n:40,sym:"Zr",name:"Zirconium",mass:"91.224",group:"transition",period:5,col:4,config:"[Kr] 4d² 5s²",state:"Solid",desc:"Extremely corrosion-resistant, used in nuclear reactor cladding and cubic zirconia gems."},
  {n:41,sym:"Nb",name:"Niobium",mass:"92.906",group:"transition",period:5,col:5,config:"[Kr] 4d⁴ 5s¹",state:"Solid",desc:"Superconductor used in MRI machines and high-strength steel alloys."},
  {n:42,sym:"Mo",name:"Molybdenum",mass:"95.96",group:"transition",period:5,col:6,config:"[Kr] 4d⁵ 5s¹",state:"Solid",desc:"High melting point metal used in steel alloys and as a cofactor in enzymes."},
  {n:43,sym:"Tc",name:"Technetium",mass:"(97)",group:"transition",period:5,col:7,config:"[Kr] 4d⁵ 5s²",state:"Solid",desc:"First artificially produced element, entirely radioactive, used in medical imaging."},
  {n:44,sym:"Ru",name:"Ruthenium",mass:"101.07",group:"transition",period:5,col:8,config:"[Kr] 4d⁷ 5s¹",state:"Solid",desc:"Rare platinum group metal used as a catalyst and in electronics."},
  {n:45,sym:"Rh",name:"Rhodium",mass:"102.91",group:"transition",period:5,col:9,config:"[Kr] 4d⁸ 5s¹",state:"Solid",desc:"One of the rarest and most valuable metals, key in catalytic converters."},
  {n:46,sym:"Pd",name:"Palladium",mass:"106.42",group:"transition",period:5,col:10,config:"[Kr] 4d¹⁰",state:"Solid",desc:"Used in catalytic converters, hydrogen purification, and jewelry."},
  {n:47,sym:"Ag",name:"Silver",mass:"107.87",group:"transition",period:5,col:11,config:"[Kr] 4d¹⁰ 5s¹",state:"Solid",desc:"The best electrical and thermal conductor of all metals, used in currency and photography."},
  {n:48,sym:"Cd",name:"Cadmium",mass:"112.41",group:"transition",period:5,col:12,config:"[Kr] 4d¹⁰ 5s²",state:"Solid",desc:"Toxic metal used in rechargeable NiCd batteries and as a nuclear reactor control rod."},
  {n:49,sym:"In",name:"Indium",mass:"114.82",group:"post-transition",period:5,col:13,config:"[Kr] 4d¹⁰ 5s² 5p¹",state:"Solid",desc:"Soft metal used in touchscreens, LCDs, and as a solder."},
  {n:50,sym:"Sn",name:"Tin",mass:"118.71",group:"post-transition",period:5,col:14,config:"[Kr] 4d¹⁰ 5s² 5p²",state:"Solid",desc:"Used since antiquity in bronze alloys, now in solder and food cans."},
  {n:51,sym:"Sb",name:"Antimony",mass:"121.76",group:"metalloid",period:5,col:15,config:"[Kr] 4d¹⁰ 5s² 5p³",state:"Solid",desc:"Used in flame retardants, semiconductors, and historically as a cosmetic."},
  {n:52,sym:"Te",name:"Tellurium",mass:"127.60",group:"metalloid",period:5,col:16,config:"[Kr] 4d¹⁰ 5s² 5p⁴",state:"Solid",desc:"Rare metalloid used in solar cells, thermoelectrics, and as a semiconductor."},
  {n:53,sym:"I",name:"Iodine",mass:"126.90",group:"halogen",period:5,col:17,config:"[Kr] 4d¹⁰ 5s² 5p⁵",state:"Solid",desc:"Essential for thyroid function, used as an antiseptic and in photography."},
  {n:54,sym:"Xe",name:"Xenon",mass:"131.29",group:"noble-gas",period:5,col:18,config:"[Kr] 4d¹⁰ 5s² 5p⁶",state:"Gas",desc:"Used in high-intensity lamps, anesthesia, and ion propulsion for spacecraft."},
  {n:55,sym:"Cs",name:"Cesium",mass:"132.91",group:"alkali",period:6,col:1,config:"[Xe] 6s¹",state:"Solid",desc:"Used in atomic clocks (defines the second), and the most electropositive element."},
  {n:56,sym:"Ba",name:"Barium",mass:"137.33",group:"alkaline",period:6,col:2,config:"[Xe] 6s²",state:"Solid",desc:"Used in medical imaging (barium meals), fireworks green color, and drilling fluids."},
  {n:57,sym:"La",name:"Lanthanum",mass:"138.91",group:"lanthanide",period:6,col:3,config:"[Xe] 5d¹ 6s²",state:"Solid",desc:"First lanthanide, used in camera lenses, hydrogen storage, and hybrid car batteries."},
  {n:58,sym:"Ce",name:"Cerium",mass:"140.12",group:"lanthanide",period:8,col:4,config:"[Xe] 4f¹ 5d¹ 6s²",state:"Solid",desc:"Most abundant lanthanide, used in catalytic converters and lighter flints."},
  {n:59,sym:"Pr",name:"Praseodymium",mass:"140.91",group:"lanthanide",period:8,col:5,config:"[Xe] 4f³ 6s²",state:"Solid",desc:"Gives glass a yellow-green color, used in aircraft engines and strong magnets."},
  {n:60,sym:"Nd",name:"Neodymium",mass:"144.24",group:"lanthanide",period:8,col:6,config:"[Xe] 4f⁴ 6s²",state:"Solid",desc:"Makes the strongest permanent magnets used in electric motors and MRI machines."},
  {n:61,sym:"Pm",name:"Promethium",mass:"(145)",group:"lanthanide",period:8,col:7,config:"[Xe] 4f⁵ 6s²",state:"Solid",desc:"Radioactive lanthanide with no stable isotopes, used in nuclear batteries."},
  {n:62,sym:"Sm",name:"Samarium",mass:"150.36",group:"lanthanide",period:8,col:8,config:"[Xe] 4f⁶ 6s²",state:"Solid",desc:"Used in samarium–cobalt permanent magnets and cancer treatments."},
  {n:63,sym:"Eu",name:"Europium",mass:"151.96",group:"lanthanide",period:8,col:9,config:"[Xe] 4f⁷ 6s²",state:"Solid",desc:"Provides red and blue colors in TV screens and is used in euro banknote security features."},
  {n:64,sym:"Gd",name:"Gadolinium",mass:"157.25",group:"lanthanide",period:8,col:10,config:"[Xe] 4f⁷ 5d¹ 6s²",state:"Solid",desc:"Used as MRI contrast agent and in nuclear reactor shielding."},
  {n:65,sym:"Tb",name:"Terbium",mass:"158.93",group:"lanthanide",period:8,col:11,config:"[Xe] 4f⁹ 6s²",state:"Solid",desc:"Used in solid-state devices, sonar, and low-energy light bulbs."},
  {n:66,sym:"Dy",name:"Dysprosium",mass:"162.50",group:"lanthanide",period:8,col:12,config:"[Xe] 4f¹⁰ 6s²",state:"Solid",desc:"Critical for high-performance magnets in EV motors and wind turbines."},
  {n:67,sym:"Ho",name:"Holmium",mass:"164.93",group:"lanthanide",period:8,col:13,config:"[Xe] 4f¹¹ 6s²",state:"Solid",desc:"Has the highest magnetic moment of any element, used in lasers and magnets."},
  {n:68,sym:"Er",name:"Erbium",mass:"167.26",group:"lanthanide",period:8,col:14,config:"[Xe] 4f¹² 6s²",state:"Solid",desc:"Adds pink color to glass and is used in fiber optic cables as an amplifier."},
  {n:69,sym:"Tm",name:"Thulium",mass:"168.93",group:"lanthanide",period:8,col:15,config:"[Xe] 4f¹³ 6s²",state:"Solid",desc:"Rarest stable lanthanide, used in portable X-ray machines and lasers."},
  {n:70,sym:"Yb",name:"Ytterbium",mass:"173.05",group:"lanthanide",period:8,col:16,config:"[Xe] 4f¹⁴ 6s²",state:"Solid",desc:"Used in stainless steel, atomic clocks, and as a dopant in fiber lasers."},
  {n:71,sym:"Lu",name:"Lutetium",mass:"174.97",group:"lanthanide",period:8,col:17,config:"[Xe] 4f¹⁴ 5d¹ 6s²",state:"Solid",desc:"Last lanthanide, used in PET scan detectors and as a catalyst."},
  {n:72,sym:"Hf",name:"Hafnium",mass:"178.49",group:"transition",period:6,col:4,config:"[Xe] 4f¹⁴ 5d² 6s²",state:"Solid",desc:"Used in nuclear control rods and microchip fabrication."},
  {n:73,sym:"Ta",name:"Tantalum",mass:"180.95",group:"transition",period:6,col:5,config:"[Xe] 4f¹⁴ 5d³ 6s²",state:"Solid",desc:"Extremely corrosion resistant, used in capacitors in mobile phones and surgical implants."},
  {n:74,sym:"W",name:"Tungsten",mass:"183.84",group:"transition",period:6,col:6,config:"[Xe] 4f¹⁴ 5d⁴ 6s²",state:"Solid",desc:"Highest melting point of all elements (3422°C), used in lightbulb filaments and drill bits."},
  {n:75,sym:"Re",name:"Rhenium",mass:"186.21",group:"transition",period:6,col:7,config:"[Xe] 4f¹⁴ 5d⁵ 6s²",state:"Solid",desc:"Second highest melting point, used in jet engine turbine blades."},
  {n:76,sym:"Os",name:"Osmium",mass:"190.23",group:"transition",period:6,col:8,config:"[Xe] 4f¹⁴ 5d⁶ 6s²",state:"Solid",desc:"Densest naturally occurring element, has a pungent and toxic oxide."},
  {n:77,sym:"Ir",name:"Iridium",mass:"192.22",group:"transition",period:6,col:9,config:"[Xe] 4f¹⁴ 5d⁷ 6s²",state:"Solid",desc:"Most corrosion-resistant metal, the KT boundary iridium anomaly marks the dinosaur extinction."},
  {n:78,sym:"Pt",name:"Platinum",mass:"195.08",group:"transition",period:6,col:10,config:"[Xe] 4f¹⁴ 5d⁹ 6s¹",state:"Solid",desc:"Precious metal used in catalytic converters, jewelry, and cancer drug cisplatin."},
  {n:79,sym:"Au",name:"Gold",mass:"196.97",group:"transition",period:6,col:11,config:"[Xe] 4f¹⁴ 5d¹⁰ 6s¹",state:"Solid",desc:"The most malleable metal, chemically inert, and humanity's oldest monetary standard."},
  {n:80,sym:"Hg",name:"Mercury",mass:"200.59",group:"transition",period:6,col:12,config:"[Xe] 4f¹⁴ 5d¹⁰ 6s²",state:"Liquid",desc:"Only metal liquid at room temperature, toxic; used in thermometers and fluorescent lamps."},
  {n:81,sym:"Tl",name:"Thallium",mass:"204.38",group:"post-transition",period:6,col:13,config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",state:"Solid",desc:"Extremely toxic, used in some infrared optical materials and historically as a poison."},
  {n:82,sym:"Pb",name:"Lead",mass:"207.2",group:"post-transition",period:6,col:14,config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",state:"Solid",desc:"Dense metal used since antiquity; neurotoxic, now phased out of paint and gasoline."},
  {n:83,sym:"Bi",name:"Bismuth",mass:"208.98",group:"post-transition",period:6,col:15,config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",state:"Solid",desc:"Most naturally diamagnetic element; forms beautiful iridescent crystals. Used in Pepto-Bismol."},
  {n:84,sym:"Po",name:"Polonium",mass:"(209)",group:"post-transition",period:6,col:16,config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",state:"Solid",desc:"Highly radioactive; discovered by Marie Curie; used in anti-static brushes and neutron initiators."},
  {n:85,sym:"At",name:"Astatine",mass:"(210)",group:"halogen",period:6,col:17,config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",state:"Solid",desc:"Rarest naturally occurring element on Earth, highly radioactive, investigated in cancer treatment."},
  {n:86,sym:"Rn",name:"Radon",mass:"(222)",group:"noble-gas",period:6,col:18,config:"[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",state:"Gas",desc:"Radioactive noble gas, second leading cause of lung cancer; seeps from uranium-containing soils."},
  {n:87,sym:"Fr",name:"Francium",mass:"(223)",group:"alkali",period:7,col:1,config:"[Rn] 7s¹",state:"Solid",desc:"Second rarest naturally occurring element; most unstable of the naturally occurring elements."},
  {n:88,sym:"Ra",name:"Radium",mass:"(226)",group:"alkaline",period:7,col:2,config:"[Rn] 7s²",state:"Solid",desc:"Discovered by Marie Curie; once used in luminous paints; highly radioactive."},
  {n:89,sym:"Ac",name:"Actinium",mass:"(227)",group:"actinide",period:7,col:3,config:"[Rn] 6d¹ 7s²",state:"Solid",desc:"First actinide; intensely radioactive; glows blue in the dark due to ionizing radiation."},
  {n:90,sym:"Th",name:"Thorium",mass:"232.04",group:"actinide",period:9,col:4,config:"[Rn] 6d² 7s²",state:"Solid",desc:"Investigated as a safer nuclear fuel alternative to uranium."},
  {n:91,sym:"Pa",name:"Protactinium",mass:"231.04",group:"actinide",period:9,col:5,config:"[Rn] 5f² 6d¹ 7s²",state:"Solid",desc:"Rare, toxic, and radioactive; intermediate in uranium-235 decay chain."},
  {n:92,sym:"U",name:"Uranium",mass:"238.03",group:"actinide",period:9,col:6,config:"[Rn] 5f³ 6d¹ 7s²",state:"Solid",desc:"Fuel for nuclear reactors and atomic bombs; denser than lead."},
  {n:93,sym:"Np",name:"Neptunium",mass:"(237)",group:"actinide",period:9,col:7,config:"[Rn] 5f⁴ 6d¹ 7s²",state:"Solid",desc:"First transuranic element, produced in nuclear reactors; used in neutron detectors."},
  {n:94,sym:"Pu",name:"Plutonium",mass:"(244)",group:"actinide",period:9,col:8,config:"[Rn] 5f⁶ 7s²",state:"Solid",desc:"Used in nuclear weapons and as fuel in spacecraft RTGs like Voyager's."},
  {n:95,sym:"Am",name:"Americium",mass:"(243)",group:"actinide",period:9,col:9,config:"[Rn] 5f⁷ 7s²",state:"Solid",desc:"Found in household smoke detectors; used in neutron gauges."},
  {n:96,sym:"Cm",name:"Curium",mass:"(247)",group:"actinide",period:9,col:10,config:"[Rn] 5f⁷ 6d¹ 7s²",state:"Solid",desc:"Named after Marie and Pierre Curie; radioactive, used in alpha particle X-ray spectrometers."},
  {n:97,sym:"Bk",name:"Berkelium",mass:"(247)",group:"actinide",period:9,col:11,config:"[Rn] 5f⁹ 7s²",state:"Solid",desc:"Named after Berkeley, California; only produced in nuclear reactors in microgram amounts."},
  {n:98,sym:"Cf",name:"Californium",mass:"(251)",group:"actinide",period:9,col:12,config:"[Rn] 5f¹⁰ 7s²",state:"Solid",desc:"Used as a neutron source to start up nuclear reactors and in cancer treatment."},
  {n:99,sym:"Es",name:"Einsteinium",mass:"(252)",group:"actinide",period:9,col:13,config:"[Rn] 5f¹¹ 7s²",state:"Solid",desc:"Discovered in the debris of the first hydrogen bomb test; named after Albert Einstein."},
  {n:100,sym:"Fm",name:"Fermium",mass:"(257)",group:"actinide",period:9,col:14,config:"[Rn] 5f¹² 7s²",state:"Solid",desc:"Named after Enrico Fermi; only produced in nuclear reactors; no stable isotopes."},
  {n:101,sym:"Md",name:"Mendelevium",mass:"(258)",group:"actinide",period:9,col:15,config:"[Rn] 5f¹³ 7s²",state:"Solid",desc:"Named after Mendeleev; first element produced one atom at a time."},
  {n:102,sym:"No",name:"Nobelium",mass:"(259)",group:"actinide",period:9,col:16,config:"[Rn] 5f¹⁴ 7s²",state:"Solid",desc:"Named after Alfred Nobel; produced in tiny amounts by nuclear bombardment."},
  {n:103,sym:"Lr",name:"Lawrencium",mass:"(266)",group:"actinide",period:9,col:17,config:"[Rn] 5f¹⁴ 7s² 7p¹",state:"Solid",desc:"Last actinide; named after Ernest Lawrence, inventor of the cyclotron."},
  {n:104,sym:"Rf",name:"Rutherfordium",mass:"(267)",group:"transition",period:7,col:4,config:"[Rn] 5f¹⁴ 6d² 7s²",state:"Solid",desc:"First transactinide element; named after Ernest Rutherford."},
  {n:105,sym:"Db",name:"Dubnium",mass:"(268)",group:"transition",period:7,col:5,config:"[Rn] 5f¹⁴ 6d³ 7s²",state:"Solid",desc:"Named after Dubna, Russia; only synthesized in particle accelerators."},
  {n:106,sym:"Sg",name:"Seaborgium",mass:"(269)",group:"transition",period:7,col:6,config:"[Rn] 5f¹⁴ 6d⁴ 7s²",state:"Solid",desc:"Named after Glenn Seaborg; only produced in labs in atom quantities."},
  {n:107,sym:"Bh",name:"Bohrium",mass:"(270)",group:"transition",period:7,col:7,config:"[Rn] 5f¹⁴ 6d⁵ 7s²",state:"Solid",desc:"Named after Niels Bohr; extremely radioactive synthetic element."},
  {n:108,sym:"Hs",name:"Hassium",mass:"(277)",group:"transition",period:7,col:8,config:"[Rn] 5f¹⁴ 6d⁶ 7s²",state:"Solid",desc:"Named after the German state Hesse; first observed in 1984."},
  {n:109,sym:"Mt",name:"Meitnerium",mass:"(278)",group:"transition",period:7,col:9,config:"[Rn] 5f¹⁴ 6d⁷ 7s²",state:"Solid",desc:"Named after physicist Lise Meitner who co-discovered nuclear fission."},
  {n:110,sym:"Ds",name:"Darmstadtium",mass:"(281)",group:"transition",period:7,col:10,config:"[Rn] 5f¹⁴ 6d⁸ 7s²",state:"Solid",desc:"Named after Darmstadt, Germany; only a few atoms have ever been produced."},
  {n:111,sym:"Rg",name:"Roentgenium",mass:"(282)",group:"transition",period:7,col:11,config:"[Rn] 5f¹⁴ 6d⁹ 7s²",state:"Solid",desc:"Named after Wilhelm Röntgen who discovered X-rays; highly unstable."},
  {n:112,sym:"Cn",name:"Copernicium",mass:"(285)",group:"transition",period:7,col:12,config:"[Rn] 5f¹⁴ 6d¹⁰ 7s²",state:"Gas",desc:"Named after Nicolaus Copernicus; may behave more like a noble gas than a metal."},
  {n:113,sym:"Nh",name:"Nihonium",mass:"(286)",group:"post-transition",period:7,col:13,config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",state:"Solid",desc:"Named after Japan (Nihon); first element discovered in Asia."},
  {n:114,sym:"Fl",name:"Flerovium",mass:"(289)",group:"post-transition",period:7,col:14,config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",state:"Solid",desc:"Named after Flerov Laboratory; may be a gas or behave like a noble gas."},
  {n:115,sym:"Mc",name:"Moscovium",mass:"(290)",group:"post-transition",period:7,col:15,config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",state:"Solid",desc:"Named after Moscow Oblast; decays rapidly within milliseconds."},
  {n:116,sym:"Lv",name:"Livermorium",mass:"(293)",group:"post-transition",period:7,col:16,config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",state:"Solid",desc:"Named after Lawrence Livermore National Laboratory; only a few atoms produced."},
  {n:117,sym:"Ts",name:"Tennessine",mass:"(294)",group:"halogen",period:7,col:17,config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",state:"Solid",desc:"Named after Tennessee; second-heaviest element, synthesized in 2010."},
  {n:118,sym:"Og",name:"Oganesson",mass:"(294)",group:"noble-gas",period:7,col:18,config:"[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",state:"Solid",desc:"Heaviest known element; named after physicist Yuri Oganessian; extremely unstable."},
];

// Group colors
const GROUP_COLORS = {
  "alkali":         "#ff6b6b",
  "alkaline":       "#ff9f43",
  "transition":     "#ffd32a",
  "post-transition":"#0abde3",
  "metalloid":      "#48dbfb",
  "nonmetal":       "#1dd1a1",
  "halogen":        "#54a0ff",
  "noble-gas":      "#a29bfe",
  "lanthanide":     "#fd79a8",
  "actinide":       "#e17055",
};

// Grid positions [row, col] for all 118
function getGridPos(el) {
  let row = el.period;
  // Lanthanides row 8, actinides row 9 (separate rows)
  if (el.group === "lanthanide") row = 8;
  if (el.group === "actinide")   row = 9;
  // La/Ac placeholder adjustment
  if (el.n === 57 || el.n === 89) { row = el.period; }
  return { row, col: el.col };
}